### ISSUE TITLE
I bricked my LB6M

### ISSUE THREAD

**Issue by sunxfof** [Fohdeesha/quanta-brocade#3]
Somehow I bricked my LB6M, now all things are dead. I believe only a JTAG can fix this.  Can you give me some information how to jtag this thing back to normal.

**Comment by Fohdeesha** [comment]
How did you brick it? have you tried pulling power to it then re-powering it and watching console output? If it's bricked, you'll need a powerPC JTAG unit like a BDI2000, which are usually more expensive than the switch. You'll also need the POWERPC-enabling firmware for the bdi2000 unit. I have one and am in the central US but you would have to pay for shipping your switch both ways

**Comment by sunxfof** [comment]
Thank you for your fast reply. A friend of mine flashed the quanta and forgot to write the bootloader into the flash. Now without any bootloader, the switch is officially brick. I have three bricked lb6m and one lb8 on my hand. Also I have two delta 7024 I’m willing to flash to dell 8024f. I have one bdi2000, but without any experience, I don’t know wherer to start. If you can shine some light on this, I will be very grateful. I’m willing to buy you some coffee with monero if you like. Thank you so much.

**Comment by Fohdeesha** [comment]
How did the other 3 lb6m's get bricked? Did they ever work or did you order them off ebay and they came like that? I ask because if they came from ebay like that, the flash chip was probably drilled out physically and they cannot be recovered?

do you know what firmware your bdi2000 has loaded?

**Comment by Fohdeesha** [comment]
Also are you in US/can speak good english? If so we can jump on google hangouts or discord voice chat sometime and I can walk you through flashing delta 7024 to dell

**Comment by sunxfof** [comment]
That’s great! I will check out my bdi2000 for the firmware version. I actually live in China. While I spent three years in CA, I think I can follow you pretty well.

**Comment by sunxfof** [comment]
How can I get in touch with you to flash the delta?

**Comment by Fohdeesha** [comment]
Do you have discord? If not we can use Google Hangouts (the web browser version). Do you have a microphone on your computer for voice communication? It will speed up the process a lot

**Comment by sunxfof** [comment]
Yes, Google Hangouts should be great. My account is sunxfof@gmail.com

**Comment by Fohdeesha** [comment]
Did you ever figure out what firmware your bdi2000 has? Would you be available around 6pm eastern time tonight?

**Comment by sunxfof** [comment]
Nope, I don't have the bdisetup tool on my hand. If you have one, I will be very grateful if you can send me the bdisetup tool to my sunxfof@gmail.com email account.  6pm Eastern Time should be 6am here. I probably haven't slept by that time. So hit me any time you feel good.

**Comment by Fohdeesha** [comment]
Do you have a null modem serial cable? You will need it for bdisetup to communicate with the bdi2000 (a straight through cable will not work). I can send you it later today

**Comment by sunxfof** [comment]
I have usb to serial , should that be suffice, if not I have ordinary serial cable and and rewire the cable according to the spec.

**Comment by Fohdeesha** [comment]
Null modem cables swap the tx and rx pins, you'll need one of those (the
serial output of a USB to serial adapter is "straight through" so it needs
a null modem cable as well. Difference is here :
https://kenarah.files.wordpress.com/2017/07/multiply_google_sheets002_zpsjtbskz4t.png?w=595

If you search Amazon for null modem cable they are very cheap

**Comment by sunxfof** [comment]
Ok I will just rewire the serial cable, change the position of tx and rx pins. Thank you very much.

**Comment by Fohdeesha** [comment]
Sounds good. You only need 3 pins, ground, tx and rx. Just make sure if you cut all the other wires they don't touch each other/short out

**Comment by sunxfof** [comment]
hi there?

**Comment by Fohdeesha** [comment]
just emailed you

**Comment by Fohdeesha** [comment]
did you get my emails last night? I will be around for the next few hours if you want to do the delta flash
