### ISSUE TITLE
Bricked LB6M Need help

### ISSUE THREAD

**Issue by moepa83** [Fohdeesha/quanta-brocade#4]
I think i bricked my LB6M. Something went wrong during flashing to brocade and I no longer can access it using the console. As soon as the switch is powered on the MGMT 1 and 2 port lights are on. The fans stay at full speed and never reduce speed. If anyone can help with this issue would really appreciate it, not looking forwarding to buying a new switch.

**Comment by Fohdeesha** [comment]
sounds like you corrupted the bootloader which means it is indeed bricked. Did you not copy/paste each command? I have a JTAG unit that can recover it, but you'll need to ship me the switch and also pay for return shipping. I'm in indianapolis, indiana if you want to calculate shipping

**Comment by moepa83** [comment]
Trying to figure out what I did wrong. I am new to flashing bootloader and this is the first time I did it. I can ship it and pay for the return shipping, can you send me the shipping address.

**Comment by Fohdeesha** [comment]
sent you a PM on STH
